# Site settings
title: Saturn Returns!
header-img: img/home-bg.jpg
email: julianaramburu@gmail.com
description: "A blog about Julian Aramburu, blogging his journey thru learning how to be a Front-End Developer"
baseurl: "/saturn-returns"
url: "http://yourdomain.com"
twitter_username: naha_hs
github_username:  julianaramburu
facebook_username:  juli.aramburu

# Build settings
markdown: kramdown
highlighter: pygments
permalink: none
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
